### ISSUE TITLE
Document teleconferences

### ISSUE THREAD

**Issue by dontcallmedom** [immersive-web/homepage#2]

**Comment by himorin** [comment]
For now, we have agendas and minutes in [administrivia repository](https://github.com/immersive-web/administrivia/tree/master/meetings), it seems better to have some part of documentation in there. Considering it, we may have two options:
- having all in administrivia repository as README.md including general information (bi-weekly for both WG/CG) and just put a link in WG website
- having several lines (or a page) of description of immersive web teleconferences in WG website, with links to two directories (WG/CG teleconference directories), and put short note as README.md in these two directories

which sounds better (or any missing requirements as 'official')??

**Comment by himorin** [comment]
then, let me push 

- a link to the administrativia repo (meetings directory) into getting involved panel
- raise ticket and PR for README.md(s) to the administrativia repo

**Comment by himorin** [comment]
although PR merged, let us keep this ticket open until immersive-web/administrivia #35 finished...

**Comment by himorin** [comment]
@dontcallmedom could you close this issue? (PR merged for both homepage and administrivia repo)
