### ISSUE TITLE
link to CoC from spec repositories

### ISSUE THREAD

**Issue by himorin** [immersive-web/homepage#36]
from https://github.com/immersive-web/homepage/pull/31

Some spec repositories have their own CoC file, which points CEPC (webxr) or CEPC + this (webxr-hand-input), etc..
Do we want to modify all to point this page?

**Comment by AdaRoseCannon** [comment]
The CoC file should just point at the CEPC which is okay if it does. otherwise it should probably be removed since the CEPC grew out of the one we created for the Immersive Web repos.

**Comment by himorin** [comment]
raised PRs.

**Comment by himorin** [comment]
closing this, all PRs merged. If any missing found, I will raise new issue (or directly push into each repo).
