### ISSUE TITLE
Add a link to RSVP for Jan 2019 FTF?

### ISSUE THREAD

**Issue by himorin** [immersive-web/homepage#7]
Are we better to add a link to RSVPs in maillist to the web? (or no need for such detail?) @dontcallmedom 
https://lists.w3.org/Archives/Public/public-immersive-web/2018Dec/0016.html

**Comment by dontcallmedom** [comment]
adding it sounds like a good idea - thanks!

**Comment by himorin** [comment]
merged, so closing this.
